agent: "PPG"
env_name: "MuJoCo"
env_id: "InvertedPendulum-v2"
vectorize: "DummyVecEnv"
representation: "Basic_MLP"
policy: "Gaussian_PPG"
runner: "DRL"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 16
running_steps: 1000000  # 1M
horizon_size: 256  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_minibatch: 4
n_epoch: 1
policy_nepoch: 2
value_nepoch: 4
aux_nepoch: 8

learning_rate: 0.0007

ent_coef: 0.0
clip_range: 0.25
kl_beta: 2.0
gamma: 0.98
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_grad_clip: False  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 10000
test_episode: 5
log_dir: "./logs/ppg/"
model_dir: "./models/ppg/"
