dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorflow"

project_name: "XuanCe_Benchmark"
logger: "wandb"  # Choices: "tensorboard", "wandb".
wandb_user_name: "1256405274"

render: True
render_mode: 'rgb_array' # Choices: 'human', 'rgb_array'.
test_mode: False

device: "cuda"  # Choices: "cpu", "cuda", "auto".


agent: "A2C"
env_name: "Box2D"
env_id: "LunarLander-v2"
vectorize: "Dummy_Gym"
policy: "Categorical_AC"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: 'LeakyReLU'

seed: 1
parallels: 10
running_steps: 300000
n_steps: 128
n_epoch: 1
n_minibatch: 1
learning_rate: 0.0004

vf_coef: 0.25
ent_coef: 0.01
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.98
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 3
log_dir: "./logs/a2c/"
model_dir: "./models/a2c/"