agent: "SAC"
env_name: "Classic Control"
env_id: "Pendulum-v1"
vectorize: "Dummy_Gym"
policy: "Gaussian_SAC"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256,]
actor_hidden_size: [256,]
critic_hidden_size: [256,]
activation: "relu"
activation_action: 'tanh'

seed: 1
parallels: 10
buffer_size: 200000
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.98
alpha: 0.2
use_automatic_entropy_tuning: True
tau: 0.005

training_frequency: 1
running_steps: 500000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 5
log_dir: "./logs/sac/"
model_dir: "./models/sac/"
