agent: "A2C"
env_name: "Classic Control"
env_id: "Pendulum-v1"
vectorize: "DummyVecEnv"
policy: "Gaussian_AC"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
actor_hidden_size: [128,]
critic_hidden_size: [128,]
activation: 'leaky_relu'
activation_action: 'tanh'

seed: 1
parallels: 10
running_steps: 1000000
horizon_size: 64  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epoch: 1
n_minibatch: 1
learning_rate: 0.0004

vf_coef: 0.25
ent_coef: 0.01
gamma: 0.98
use_gae: True
gae_lambda: 0.95
use_advnorm: True

use_grad_clip: True  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 3
log_dir: "./logs/a2c/"
model_dir: "./models/a2c/"
