agent: "PG"
env_name: "MuJoCo"
env_id: "Ant-v4"
vectorize: "Dummy_Gym"
policy: "Gaussian_Actor"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256, 256]
actor_hidden_size: []
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 16
running_steps: 1000000  # 1M
horizon_size: 256  # the horizon size for an environment, buffer_size = horizon_size * parallels.
n_epoch: 1
n_minibatch: 1
learning_rate: 0.0007  # 7e-4

ent_coef: 0.0
clip_grad: 0.5
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
gamma: 0.99
use_gae: False
gae_lambda: 0.95
use_advnorm: False

use_obsnorm: True
use_rewnorm: True
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 5000
test_episode: 5
log_dir: "./logs/pg/"
model_dir: "./models/pg/"