agent: "OWQMIX"  # choice: CWQMIX, OWQMIX
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "Weighted_Mixing_Q_network"
representation: "Basic_MLP"
vectorize: "Dummy_Pettingzoo"
runner: "Pettingzoo_Runner"
on_policy: False

use_recurrent: False
rnn: "GRU"
recurrent_layer_N: 1
fc_hidden_sizes: [ 64, ]
recurrent_hidden_size: 64
N_recurrent_layers: 1
dropout: 0

representation_hidden_size: [128, ]  # for Basic_MLP representation
q_hidden_size: [128, ]  # the units for each hidden layer
activation: "relu"
alpha: 0.1

hidden_dim_mixing_net: 32  # hidden units of mixing network
hidden_dim_hyper_net: 64  # hidden units of hyper network
hidden_dim_ff_mix_net: 256  # hidden units of mixing network

seed: 1
parallels: 16
buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.99  # discount factor
double_q: True  # use double q learning

start_greedy: 1.0
end_greedy: 0.05
decay_step_greedy: 5000000
start_training: 1000  # start training after n episodes
running_steps: 10000000  # 10M
train_per_step: False  # True: train model per step; False: train model per episode.
training_frequency: 1
sync_frequency: 200

use_grad_clip: False
grad_clip_norm: 0.5

eval_interval: 100000
test_episode: 5
log_dir: "./logs/wqmix/"
model_dir: "./models/wqmix/"
