agent: "DCG"  # Options: DCG, DCG_S
env_name: "mpe"
env_id: "simple_spread_v3"
continuous_action: False
policy: "DCG_Policy"
representation: "Basic_MLP"
vectorize: "Dummy_Pettingzoo"
runner: "Pettingzoo_Runner"
on_policy: False

use_recurrent: False
rnn:
representation_hidden_size: [32, ]
q_hidden_size: [128, ]  # the units for each hidden layer
hidden_utility_dim: 256  # hidden units of the utility function
hidden_payoff_dim: 256  # hidden units of the payoff function
bias_net: "Basic_MLP"
hidden_bias_dim: [256, ]  # hidden units of the bias network with global states as input
activation: "relu"

low_rank_payoff: False  # low-rank approximation of payoff function
payoff_rank: 5  # the rank K in the paper
graph_type: "FULL"  # specific type of the coordination graph
n_msg_iterations: 1  # number of iterations for message passing during belief propagation
msg_normalized: True  # Message normalization during greedy action selection (Kok and Vlassis, 2006)

seed: 1
parallels: 16
buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.95  # discount factor
double_q: True  # use double q learning

start_greedy: 1.0
end_greedy: 0.05
decay_step_greedy: 2500000
start_training: 1000  # start training after n episodes
running_steps: 10000000  # 10M
train_per_step: False  # True: train model per step; False: train model per episode.training_frequency: 1
training_frequency: 1
sync_frequency: 200

use_grad_clip: False
grad_clip_norm: 0.5

eval_interval: 100000
test_episode: 5
log_dir: "./logs/dcg/"
model_dir: "./models/dcg/"

