agent: "MPDQN"
env_name: "Platform"
env_id: "Platform-v0"
vectorize: "NOREQUIRED"
render: False
policy: "MPDQN_Policy"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
conactor_hidden_size: [128,]
qnetwork_hidden_size: [128, ]
activation: "relu"
activation_action: 'tanh'

buffer_size: 20000
batch_size: 128
learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_greedy: 0.5
end_greedy: 0.05
decay_step_greedy: 1000000  # 1M
start_noise: 0.1
end_noise: 0.1
training_frequency: 1
running_steps: 30000
start_training: 1000

test_steps: 10000
eval_interval: 1000
test_episode: 5

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

log_dir: "./logs/mpdqn/"
model_dir: "./models/mpdqn/"

