agent: "QRDQN"
env_name: "Classic Control"
env_id: "MountainCar-v0"
env_seed: 1
vectorize: "DummyVecEnv"
learner: "QRDQN_Learner"
policy: "QR_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
q_hidden_size: [128,]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 200000
batch_size: 256
learning_rate: 0.001
gamma: 0.99
quantile_num: 20

start_greedy: 0.25
end_greedy: 0.01
decay_step_greedy: 300000
sync_frequency: 100
training_frequency: 1
running_steps: 300000
start_training: 1000

use_grad_clip: False  # gradient normalization
clip_type: 1  # Gradient clip for Mindspore: 0: ms.ops.clip_by_value; 1: ms.nn.ClipByNorm()
grad_clip_norm: 0.5
use_actions_mask: False
use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 1
log_dir: "./logs/qrdqn/"
model_dir: "./models/qrdqn/"
