agent: "ExpoComm"
env_name: "SMACv2"
env_id: "10gen_terran"
env_seed: 1
fps: 15
device: "cuda:0"
learner: "ExpoComm_Learner"
policy: "ExpoComm_Q_network"
representation: "Basic_RNN"
vectorize: "Subproc_StarCraft2"
runner: "RunnerStarCraft2"

n_units: 20
n_enemies: 20
unit_types: ["marine", "marauder", "medivac"]
unit_weights: [0.8, 0.2, 0]
exception_unit_types: ["medivac"]
start_dist_type: "surrounded_and_reflect"
start_p: 0.5
map_x: 32
map_y: 32

use_rnn: True
rnn: "GRU"
N_recurrent_layers: 1
fc_hidden_sizes: [64, 64, ]
recurrent_hidden_size: 64
dropout: 0

representation_hidden_size: [64, ]
q_hidden_size: [64, 32]
activation: "relu"
use_parameter_sharing: True
use_actions_mask: True

hidden_dim_mixing_net: 64
hidden_dim_hyper_net: 64

seed: 1
parallels: 8
buffer_size: 5000
batch_size: 64
learning_rate: 0.0007
gamma: 0.99
double_q: True

topk: 7
aux_coef: 0.1
attention_dim: 32
one_peer: True

start_greedy: 1.0
end_greedy: 0.05
decay_step_greedy: 100000
start_training: 2000
running_steps: 5000000
n_epochs: 8
sync_frequency: 200

td_lambda: 0.4

use_grad_clip: False
grad_clip_norm: 0.5

eval_interval: 50000
test_episode: 32

log_dir: "logs/qmix_smacv2/"
model_dir: "models/qmix_smacv2/"
