dl_toolbox: "torch"  # The deep learning toolbox. Choices: "torch", "mindspore", "tensorlayer"
project_name: "XuanCe_Benchmark"
logger: "tensorboard"  # Choices: tensorboard, wandb.
wandb_user_name: "your_user_name"
render: True
render_mode: 'human' # Choices: 'human', 'rgb_array'.
test_mode: False
device: "cuda:0"

agent: "DQN"
env_name: "BlackjackEnv"
env_id: "blackjack-v0"
vectorize: "Dummy_BlackjackEnv"
policy: "Basic_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
q_hidden_size: [128,]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 10000
batch_size: 256
learning_rate: 0.001
gamma: 0.99

start_greedy: 0.9
end_greedy: 0.01
decay_step_greedy: 10000
sync_frequency: 50
training_frequency: 1
running_steps: 200000  # 200k
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 50000
eval_interval: 20000
test_episode: 10
log_dir: "./logs/dqn/"
model_dir: "./models/dqn/"