agent: "MADDPG"  # the learning algorithms_marl
env_name: "Drones"
env_id: "MultiHoverAviary"
obs_type: 'kin'
act_type: 'vel'
num_drones: 3
record: False
obstacles: True
max_episode_steps: 1000
render: False
sleep: 0.01
policy: "MADDPG_Policy"
representation: "Basic_Identical"
vectorize: "Dummy_Drone_MAS"
runner: "MARL"
on_policy: False

actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: 'leaky_relu'
activation_action: 'tanh'

seed: 1
parallels: 10
buffer_size: 1000000
batch_size: 1024
lr_a: 0.001  # learning rate for actor
lr_c: 0.001  # learning rate for critic
gamma: 0.99  # discount factor
tau: 0.005  # soft update for target networks

start_noise: 0.1
end_noise: 0.1
sigma: 0.1
start_training: 2000  # start training after n episodes
running_steps: 10000000
train_per_step: True  # True: train model per step; False: train model per episode.
training_frequency: 1

use_grad_clip: True
grad_clip_norm: 0.5

eval_interval: 100000
test_episode: 5
log_dir: "./logs/maddpg/"
model_dir: "./models/maddpg/"
