agent: "C51DQN"
env_name: "Box2D"
env_id: "LunarLander-v2"
vectorize: "Dummy_Gym"
policy: "C51_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [128,]
q_hidden_size: [128,]
activation: 'relu'

seed: 1
parallels: 10
buffer_size: 200000
batch_size: 256
learning_rate: 0.001
gamma: 0.99
vmin: 0
vmax: 200
atom_num: 51

start_greedy: 0.5
end_greedy: 0.01
decay_step_greedy: 10000
sync_frequency: 100
training_frequency: 1
running_steps: 200000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 1
log_dir: "./logs/c51/"
model_dir: "./models/c51/"
