agent: "C51DQN"  # Name of agent
vectorize: "Dummy_Atari"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
env_seed: 1  # Random seed for the environment.
obs_type: "grayscale"  # choice for Atari env: ram, rgb, grayscale
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
learner: "C51_Learner"  # Name of the learner.
policy: "C51_Q_network"  # Name of the policy.
representation: "Basic_CNN"
runner: "DRL"  # Name of the runner.

# the following three arguments are for "Basic_CNN" representation.
filters: [32, 64, 64]  #  [16, 16, 32, 32]
kernels: [8, 4, 3]  # [8, 6, 4, 4]
strides: [4, 2, 1]  # [2, 2, 2, 2]

q_hidden_size: [512, ]  # The hidden units for Q-network.
activation: "relu"  # The activation function of each hidden layer.

seed: 1069  # The random seed.
parallels: 5  # Number of environments that to be implemented in parallel.
buffer_size: 500000  # The size of replay buffer
batch_size: 32  # The batch size for training.
learning_rate: 0.0001  # The learning rate.
gamma: 0.99  # The discount factor.
v_min: 0
v_max: 200
atom_num: 51

start_greedy: 0.5  # The start epsilon greedy.
end_greedy: 0.05  # The end epsilon greedy.
decay_step_greedy: 10000000  # Number of steps for the decay of epsilon greedy.
sync_frequency: 500  # The frequency to update target networks.
training_frequency: 1  # The frequency to update the RL model.
running_steps: 50000000  # The total running steps.
start_training: 10000  # The running steps before training.

use_grad_clip: False  # gradient normalization
grad_clip_norm: 0.5  # The norm value for gradient clip.
use_actions_mask: False  # Whether to use actions mask when the environment provides available actions values.
use_obsnorm: False  # Whether to use observation normalization trick.
use_rewnorm: False  # Whether to use reward normalization trick.
obsnorm_range: 5  # The observation normalization range.
rewnorm_range: 5  # The reward normalization range.

test_steps: 10000  # Number of steps to test the model.
eval_interval: 500000  # Frequency to evaluate the model.
test_episode: 3  # Number of episodes to test.
log_dir: "./logs/c51/"  # The directory to store logger file.
model_dir: "./models/c51/"  # The directory to store model file.
