agent: "DQN"
env_name: "Classic Control"
env_id: "MountainCar-v0"
vectorize: "Dummy_Gym"
policy: "Basic_Q_network"
representation: "Basic_MLP"
runner: "DRL"

representation_hidden_size: [256, ]
q_hidden_size: [256, ]
activation: 'leaky_relu'

seed: 1
parallels: 10
buffer_size: 200000
batch_size: 256
learning_rate: 0.1
gamma: 0.99

start_greedy: 1.0
end_greedy: 0.01
sync_frequency: 200
training_frequency: 2
running_steps: 2000000  # 2M
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 50000
test_episode: 5
log_dir: "./logs/dqn/"
model_dir: "./models/dqn/"
