agent: "SACDIS"
vectorize: "Dummy_Atari"
env_name: "Atari"
env_id: "ALE/Breakout-v5"
obs_type: "grayscale"  # choice for Atari env: ram, rgb, grayscale
img_size: [84, 84]  # default is 210 x 160 in gym[Atari]
num_stack: 4  # frame stack trick
frame_skip: 4  # frame skip trick
noop_max: 30  # Do no-op action for a number of steps in [1, noop_max].
representation: "Basic_CNN"
policy: "Discrete_SAC"
runner: "DRL"

filters: [32, 32, 64, 64]
kernels: [8, 4, 4, 4]
strides: [4, 2, 2, 2]
actor_hidden_size: [128, 128]
critic_hidden_size: [128, 128]
activation: "leaky_relu"

seed: 1069
parallels: 5
buffer_size: 500000
batch_size: 32  # 64
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
alpha: 0.01
use_automatic_entropy_tuning: False
tau: 0.005

training_frequency: 1
running_steps: 50000000  # 50M
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 500000
test_episode: 1
log_dir: "./logs/sac/"
model_dir: "./models/sac/"
