agent: "SAC"
env_name: "MuJoCo"
env_id: "Ant-v4"
vectorize: "Dummy_Gym"
policy: "Gaussian_SAC"
representation: "Basic_Identical"
runner: "DRL"

representation_hidden_size:
actor_hidden_size: [256, 256]
critic_hidden_size: [256, 256]
activation: "leaky_relu"
activation_action: 'tanh'

seed: 1
parallels: 4  # number of environments
buffer_size: 1000000
batch_size: 256
actor_learning_rate: 0.001
critic_learning_rate: 0.001
gamma: 0.99
alpha: 0.2
use_automatic_entropy_tuning: True
tau: 0.005

training_frequency: 1
running_steps: 1000000
start_training: 10000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

test_steps: 10000
eval_interval: 10000
test_episode: 5
log_dir: "./logs/sac/"
model_dir: "./models/sac/"
